### ISSUE TITLE
Evaluation of the whole thing

### ISSUE THREAD

**Issue by C0DK** [Trivivium/devops-2k20#116]
Describe the biggest issues, how you solved them, and which are major lessons learned with regards to:

Evolution and refactoring operation, and maintenanceof your ITU-MiniTwit systems. Link back to respective commit messages, issues, tickets, etc. to illustrate these.

We should all contribute to the evaluation and talk about what we've each learned and would/have done differently compared to prior projects

**Comment by Trivivium** [comment]
Short note: As mentioned in commit 0237dcd21efa20c1d875bfd8ddf75bf98d7c4409 I removed the evaluation section related to the choice of OS as I think we should consider adding it the general evaluation of the project.

**Comment by Trivivium** [comment]
Database
- Lack of automated database backups

Application

- Not persisting authentication signing key outside container.
- Not reacting to exceptions early enough meant we lost A LOT of registrations causing future operations to fail. Something that would haunt us for the rest of the course. (is mentioned briefly)
- Due to the above exceptions our SLA wasn't in terms of errors pr. hour and mean time to recover

	
CI/CD

- Tests provision an entire setup using Docker. This could be faster using in-memory testing of ASPNET Core in C# XUnit integration tests
- No option to skip the pipeline
	
Development practices

- 	Not always following our own contribution guidelines

**Comment by Trivivium** [comment]
Hi @Akons97, I've added a couple of sections to the evaluation chapter. The changes can be seen in commit 21bb17cf9051466e92d575b348b85acf8e349596. Do you have time to review the changes, and add any comments?
