### ISSUE TITLE
Describe Distributed Workflow

### ISSUE THREAD

**Issue by C0DK** [Trivivium/devops-2k20#29]
it's in [this](https://github.com/itu-devops/2020-spring/blob/master/sessions/session_02/Session%202.ipynb) at the same title as the headline

**Comment by Trivivium** [comment]
_Copied from the course slides:_

Think about, discuss in your groups, and note down in which way you are going to collaborate using Git in this project.

You should reflect and decide on the following points:

- Which repository setup will we use?
- Which branching model will we use?
- Which distributed development workflow will we use?
- How do we expect contributions to look like?
- Who is responsible for integrating/reviewing contributions?

Information to at least all of the above points should end up in a markdown document in your main repository (likely called `CONTRIBUTE.md`).

**Comment by Trivivium** [comment]
Answers to the points:

1. Mono repository: Both of the applications are in the same repository
2. Feature branching
3. Centralized workflow: All developers commit/branch off of the same repository.
4. Contributions should be based in an issue with a separate branch. When the code should be merged into master a PR referencing the issue in the comment should be created. All issues should aim to labelled accordingly and have a milestone associated where necessary.
5. All PRs should aim to be reviewed by at least 1 other developer. The reviewer should then merge the PR.

Do you agree with this? It's a rough outline and we're properly going to adjust it many times. I know I've "broken" rule 4 once at least, so we should get this decided sooner rather than later.

**Comment by C0DK** [comment]
feature branching is not the term. it's called trunk based development

**Comment by C0DK** [comment]
but otherwise yeah

**Comment by Trivivium** [comment]
@C0DK As far as I could research is it correct. Trunk based development is the overall workflow, but the branching model used is still feature branching
